services:
  - type: web
    name: farmlink-backend
    env: python
    plan: free
    region: frankfurt
    buildCommand: pip install -r backend/requirements.txt
    startCommand: cd backend && uvicorn app:app --host 0.0.0.0 --port 10000
    envVars:
      - key: QDRANT_URL
        sync: false
      - key: QDRANT_API_KEY
        sync: false
      - key: LLM_API_KEY
        sync: false
      - key: LLM_MODEL
        value: mistral-small
      - key: QDRANT_ACTIVE_COLLECTIONS
        value: farmlink_marche,farmlink_sols,farmlink_eau,farmlink_meca
